### ISSUE TITLE
Feature #1: User can see a Google maps.

### ISSUE THREAD

**Issue by SeungjooKimSJ** [SeungjooKimSJ/place-advisor#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Users can see the frame of a page containing Google Maps.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

will be added later...

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

will be added later...

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [ ] Create a 
- [ ] Update `schema.sql` to make a table to store the data.
- [ ] Update `data.sql` to make a table to store the data.

### ☁️ Server

- [ ] Create `server/index.js` to store transaction data that handle the POST request, including an auto-generated Id property.
- [ ] Add Put method to update the date, category, amount, and description.
- [ ] Test it in the terminal.
- [ ] Handle all errors and response status code to the client.

### ⚡ Client

- [ ] Create a component for each modal form tab on the add transaction page.
- [ ] Update component to match the result of what I selected.

### 🧑‍⚕️ Clean Up

- [ ] Create an add transaction page like my wireframe that contains a header, form, and footer.
- [ ] Add form event listeners on the Save button.
- [ ] Add click event listener that responds to deposit and withdrawal buttons.
- [ ] Add date input and select element for the date and category.
- [ ] Ensure to check saved transaction stores in the local storage.
- [ ] Ensure to check the Cancel button make go back to the previous page.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all console logs, comment out code or CSS properties that have no effect.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on mobile screens.
